sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GOB/q7p4w838zUog2fMsEo2gcAKWrJDudzoVDk4ySE/ldBvbque9zGbYczV6l8DNv96J50aNKkVqNn/+CiqdcDCh0HQBrt39Tz7K4JJH6nlgTV26sa42YExZID79O9bvZkhEea2+vkdNevSSW4T51I6Q2dbw0Rl2hXsfSI/7pwn7vKiZ1EiNyTraClXRnhInvtUZnt/Awms5Oxjlf/KxaV4BccHiRdFHGK4OYFMRkaU2xNabXSDExsmknKmwNmFA3UyZo8LX+nF/Qs4KWQIeOweiZABWhwhtvVOh5+411vEnv/JtsGjepNn98SJNI5Z9Ur5lZon0tQlPgMOBXGf06CZIPh4/461XF1cAsMz0YSTVoHCDATdz9UgOzifG6pK950QPf7Z0W4Nap9wtH69XWJi/Nxt/Vg9e3dAUAlTbOs3SZPNEbNvfIff9fXvku7KnV+QZsEqm1Lh2/tRxdsUAckLSShaJaFW8hkGR4WwRPfIwTmQMvwYwBVeJphzX3Zs8N63jIMcGLJbRpYBgCUtk14lG+NwCcG9xxVTGHCh/Jo8WUHlKo0+gwZcShokgxvtw33Gyws9d2MtsEWBI8Nfqo29FSfZ9kUekUqV0VQlXOjsEL6iFVB7FDb8Wkw8ZpaoITH7WCYPGAx8Clzuf3rGXmXRmh8b4hte/7pez0cm0Z/E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Renascence-and-Other-Poems_109
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy